<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Akun_Ikhsan Nur Syahbanu</name>
   <tag></tag>
   <elementGuidId>2ff20e10-335f-43ef-95eb-0501a5048a21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h5.name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='customer_detail']/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>c4b3f29e-8009-43d8-9930-8b93195bfb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>1e501888-fc22-4528-bf41-e771da324350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ikhsan Nur Syahbanu</value>
      <webElementGuid>890fc85f-e23a-46f6-9810-99a4bc271c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_detail&quot;)/h5[@class=&quot;name&quot;]</value>
      <webElementGuid>b2fdd8eb-0436-4900-925e-e6929b28d8b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_detail']/h5</value>
      <webElementGuid>1bef731d-d8c7-4665-951a-0eff68cbe550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[1]/following::h5[1]</value>
      <webElementGuid>03410e79-2691-407d-8352-ba18c1dbab17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::h5[1]</value>
      <webElementGuid>6555a96a-2f05-474f-870c-0d2f538da7a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Addresses (1)'])[1]/preceding::h5[1]</value>
      <webElementGuid>3d12383a-06c0-4fbe-96df-28a6432e7add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='phone'])[1]/preceding::h5[1]</value>
      <webElementGuid>08c5558e-2476-4ab2-85e6-88739751352d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ikhsan Nur Syahbanu']/parent::*</value>
      <webElementGuid>2cc93fa2-3374-4d9f-8cae-4a3d99a608da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>34365ad9-697d-4e17-bd28-ee65bca7d6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Ikhsan Nur Syahbanu' or . = 'Ikhsan Nur Syahbanu')]</value>
      <webElementGuid>7c143172-8e84-4a13-a98c-487ada4842fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
