<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Akun_My Account</name>
   <tag></tag>
   <elementGuidId>7a4d3f3a-bdd8-4b25-89a3-16779d9262be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='admin_header']/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>2073a32a-fb07-4585-a68a-7dd712fea6bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>e6938900-1ce9-4308-b792-89003338ac31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Account</value>
      <webElementGuid>1d796442-46f2-4cb7-a6cf-a90088c8f683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admin_header&quot;)/h2[@class=&quot;title&quot;]</value>
      <webElementGuid>5b76faa8-8c80-48dc-99bd-594af8bd68a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admin_header']/h2</value>
      <webElementGuid>b9fddfbd-1133-4944-bdee-56a5c1929a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::h2[1]</value>
      <webElementGuid>9da50d19-3a93-41f5-aaf9-5c099ec40db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return to Store'])[1]/following::h2[1]</value>
      <webElementGuid>7cfe4e12-d018-4fc7-a0e6-8f2b53e92dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ikhsan Nur Syahbanu'])[1]/preceding::h2[1]</value>
      <webElementGuid>080da712-5f88-4336-97c6-a7008aa6a305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Addresses (1)'])[1]/preceding::h2[1]</value>
      <webElementGuid>37854ddd-85e5-4541-bac3-d66e907bce18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Account']/parent::*</value>
      <webElementGuid>5c97204a-652e-4297-ac46-eaafb5428eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>79aa54a0-0b2a-4f65-949e-3afcbbfceade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'My Account' or . = 'My Account')]</value>
      <webElementGuid>bd55d452-1205-4a53-8c06-209f1d7c4405</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
