<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Register_Button buat akun</name>
   <tag></tag>
   <elementGuidId>7d05beb3-aa1b-4dbf-b250-7b76e03e21c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submitbtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submitbtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5ab00f02-73e9-4ed6-984a-3297eed73068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af87a18a-442b-4495-b5f4-3f600021b18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitbtn</value>
      <webElementGuid>f24d8357-3925-4804-9c2c-c046736d53c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-buatakun</value>
      <webElementGuid>04c73fee-4c91-48f4-bf0f-d92dd4df7f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BUAT AKUN</value>
      <webElementGuid>a4466b4f-4250-4d00-be8a-7c442ddde11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitbtn&quot;)</value>
      <webElementGuid>de6c46d7-41b8-4e7e-873e-f6228515c3b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submitbtn']</value>
      <webElementGuid>95462ee4-9f2d-4d5c-af09-fbf70a565a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='RegisterForm']/div[10]/button</value>
      <webElementGuid>b2b6737e-1f59-46e5-9f07-93242b9172c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beritahu saya penawaran dan informasi ekslusif Executive melalui email'])[1]/following::button[1]</value>
      <webElementGuid>0135cc7c-60f1-44ec-994e-e9e729dcb1d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pria'])[1]/following::button[1]</value>
      <webElementGuid>44a42557-c19a-4588-844f-0ecc1f86f303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='phone'])[1]/preceding::button[1]</value>
      <webElementGuid>34577110-3409-48da-853d-6053cb48b944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need Help'])[1]/preceding::button[1]</value>
      <webElementGuid>92b03f15-b02b-4e28-b72f-803f631029f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BUAT AKUN']/parent::*</value>
      <webElementGuid>040b3e95-4271-417a-a650-3df8df345fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/button</value>
      <webElementGuid>bd5beb31-2028-4ac4-b498-81f8ec1d202e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'submitbtn' and (text() = 'BUAT AKUN' or . = 'BUAT AKUN')]</value>
      <webElementGuid>6d37ee71-1dc9-4dcc-9748-fbe57d9f270c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
