<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Register_field tanggal lahir</name>
   <tag></tag>
   <elementGuidId>4e1596c8-b042-42c0-b010-52224ad2946d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#birthday</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='birthday']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7901816c-ffc5-4642-8558-41e350610e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2fc85c05-2764-4c0a-99ae-9421c0f59154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer[note][birthday]</value>
      <webElementGuid>53bdc238-000f-4e60-977b-d64160bde692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birthday</value>
      <webElementGuid>9145c804-39ce-4048-9fcd-5d830cc48991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>large</value>
      <webElementGuid>e5cb8a06-adf9-45a8-a36c-d3a68a1baa28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;birthday&quot;)</value>
      <webElementGuid>061ae7e2-6654-4593-850b-0da46892764a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='birthday']</value>
      <webElementGuid>a923bf41-e279-4365-b3e0-7467a60d0401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tgllahir']/input</value>
      <webElementGuid>a9fd26ec-d3ec-493b-ab12-5a914b82e9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>c53e6708-5495-43a2-9ad2-28cc8c206b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'customer[note][birthday]' and @id = 'birthday']</value>
      <webElementGuid>59aaf34b-f17d-413b-ac1f-d9ae02573988</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
