<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Register_radio button pria</name>
   <tag></tag>
   <elementGuidId>a7094b36-2842-4a5f-a59a-43e6afd24999</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pria</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pria']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5931aad1-3f0b-4e2e-971f-42d413f782cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b5c4339f-e080-49e7-b41c-914c4b42d329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pria</value>
      <webElementGuid>8ce8e075-3645-46dd-84b6-07d5612715d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer[note][gender]</value>
      <webElementGuid>969de506-0c79-45af-b675-187e44e87215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pria</value>
      <webElementGuid>0445ca3d-e091-4983-a869-4e911f8c1629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pria&quot;)</value>
      <webElementGuid>0110c6d0-3ccc-4e20-b186-799106f38826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pria']</value>
      <webElementGuid>e4fd6147-8b4b-405a-a0c9-7ee879b5e793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='RegisterForm']/div[8]/div/div[2]/input</value>
      <webElementGuid>49b89f82-372c-4d81-8d21-f9dfc30ea01b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>538a7fe7-cbfb-4482-81ed-71454bad93f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'pria' and @name = 'customer[note][gender]']</value>
      <webElementGuid>d8b44834-a73a-4356-83b4-b88c35662809</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
